const { Workshop } = require('ldcli');

module.exports = function() {
    var workshop = Workshop({  name: "FullBlast Academy of Game", slug: "full-blast-academy-of-game", description: "A workshop to make a Game!" });

  workshop.Concept({ name: "Intro to Phaser", slug: "intro-to-phaser", draftMode: false })
  .Action({ name: "Context", slug: "context", draftMode: false, visibilityLevel: 1 })
  .Action({ name: "Goal & Starting Point", slug: "goal-&-startingpoint", draftMode: false, visibilityLevel: 1 })
  .Action({ name: "Phaser Cycle", slug: "phaser-cycle", draftMode: false, visibilityLevel: 1 })
  .Action({ name: "Readings", slug: "readings", draftMode: false, visibilityLevel: 1 })
.Concept({ name: "Game", slug: "game", draftMode: true })
  .Action({ name: "Uncovering Secrets", slug: "uncovering-secrets", draftMode: false, visibilityLevel: 2 })
  .Action({ name: "Improper Access", slug: "improper-access", draftMode: false, visibilityLevel: 2 })
  .Action({ name: "Injection", slug: "injection", draftMode: false, visibilityLevel: 2 })
  .Action({ name: "XSS", slug: "xss", draftMode: false, visibilityLevel: 2 })
  .Action({ name: "Data Theft", slug: "data-theft", draftMode: false, visibilityLevel: 2 })
  .Action({ name: "Session Hijacking", slug: "session-hijacking", draftMode: true, visibilityLevel: 2 })
  .Action({ name: "XSRF", slug: "xsrf", draftMode: true, visibilityLevel: 2 })
  .Action({ name: "DoS", slug: "do-s", draftMode: true, visibilityLevel: 2 })
  .Action({ name: "Phishing", slug: "phishing", draftMode: true, visibilityLevel: 2 })
.Concept({ name: "Uncovering Secrets (old)", slug: "uncovering-secrets-old", draftMode: true })
  .Action({ name: "Background", slug: "background", draftMode: false, visibilityLevel: 2 })
  .Action({ name: "Attack", slug: "attack", draftMode: true, visibilityLevel: 2 })
  .Action({ name: "Attack Scorecard", slug: "attack-scorecard", draftMode: true, visibilityLevel: 2 })
  .Action({ name: "Defense", slug: "defense", draftMode: false, visibilityLevel: 2 })
.Concept({ name: "Improper Access (old)", slug: "improper-access-old", draftMode: true })
  .Action({ name: "Background", slug: "background", draftMode: false, visibilityLevel: 2 })
  .Action({ name: "Attack", slug: "attack", draftMode: false, visibilityLevel: 2 })
  .Action({ name: "Attack Scorecard", slug: "attack-scorecard", draftMode: false, visibilityLevel: 2 })
  .Action({ name: "Defense", slug: "defense", draftMode: false, visibilityLevel: 2 })
.Concept({ name: "Injection (old)", slug: "injection-old", draftMode: true })
  .Action({ name: "Background", slug: "background", draftMode: false, visibilityLevel: 2 })
  .Action({ name: "Attack", slug: "attack", draftMode: false, visibilityLevel: 2 })
  .Action({ name: "Defense", slug: "defense", draftMode: false, visibilityLevel: 2 })
.Concept({ name: "XSS (old)", slug: "xss-old", draftMode: true })
  .Action({ name: "Background", slug: "background", draftMode: false, visibilityLevel: 2 })
  .Action({ name: "Attack", slug: "attack", draftMode: false, visibilityLevel: 2 })
  .Action({ name: "Defense", slug: "defense", draftMode: false, visibilityLevel: 2 })
.Concept({ name: "Data Theft (old)", slug: "data-theft-old", draftMode: true })
  .Action({ name: "Background", slug: "background", draftMode: false, visibilityLevel: 2 })
  .Action({ name: "Attack", slug: "attack", draftMode: false, visibilityLevel: 2 })
  .Action({ name: "Defense", slug: "defense", draftMode: false, visibilityLevel: 2 })
.Concept({ name: "Covering Secrets", slug: "covering-secrets", draftMode: false })
  .Action({ name: "Background", slug: "background", draftMode: false, visibilityLevel: 2 })
  .Action({ name: "Defend", slug: "defend", draftMode: false, visibilityLevel: 2 })
.Concept({ name: "Proper Access Control", slug: "proper-access-control", draftMode: false })
  .Action({ name: "Background", slug: "background", draftMode: false, visibilityLevel: 2 })
  .Action({ name: "Defend", slug: "defend", draftMode: false, visibilityLevel: 2 })
.Concept({ name: "Injection", slug: "injection", draftMode: false })
  .Action({ name: "Background", slug: "background", draftMode: false, visibilityLevel: 2 })
  .Action({ name: "Defend", slug: "defend", draftMode: false, visibilityLevel: 2 })
.Concept({ name: "XSS", slug: "xss", draftMode: false })
  .Action({ name: "Backgound", slug: "backgound", draftMode: false, visibilityLevel: 2 })
  .Action({ name: "Defend", slug: "defend", draftMode: false, visibilityLevel: 2 })
.Concept({ name: "Oversharing", slug: "oversharing", draftMode: false })
  .Action({ name: "Background", slug: "background", draftMode: false, visibilityLevel: 2 })
  .Action({ name: "Defend", slug: "defend", draftMode: false, visibilityLevel: 2 })
.Concept({ name: "Hash the Pass", slug: "hash-the-pass", draftMode: false })
  .Action({ name: "Background", slug: "background", draftMode: false, visibilityLevel: 2 })
  .Action({ name: "Defend", slug: "defend", draftMode: false, visibilityLevel: 2 })
.Concept({ name: "Broken Auth", slug: "broken-auth", draftMode: false })
  .Action({ name: "Background", slug: "background", draftMode: false, visibilityLevel: 2 })
  .Action({ name: "Defend", slug: "defend", draftMode: false, visibilityLevel: 2 })
.Concept({ name: "Transport Security", slug: "transport-security", draftMode: false })
  .Action({ name: "Background", slug: "background", draftMode: false, visibilityLevel: 2 })
  .Action({ name: "Defend", slug: "defend", draftMode: false, visibilityLevel: 2 })
.Concept({ name: "Conclusion", slug: "conclusion", draftMode: false })
  .Action({ name: "Review", slug: "review", draftMode: false, visibilityLevel: 2 })

return workshop;
}
